// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMrPY7HinNwtWGFWdxjwLtBP7rjJWwsIw',
    appId: '1:787300819292:web:49567c1effbe811a2ce199',
    messagingSenderId: '787300819292',
    projectId: 'salas-and-beats',
    authDomain: 'salas-and-beats.firebaseapp.com',
    storageBucket: 'salas-and-beats.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrPY7HinNwtWGFWdxjwLtBP7rjJWwsIw',
    appId: '1:787300819292:android:49567c1effbe811a2ce199',
    messagingSenderId: '787300819292',
    projectId: 'salas-and-beats',
    storageBucket: 'salas-and-beats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlJjFhvaru7CHa5D4ivJYlVplwb8lbn10',
    appId: '1:787300819292:ios:3d184b81a2e636762ce199',
    messagingSenderId: '787300819292',
    projectId: 'salas-and-beats',
    storageBucket: 'salas-and-beats.firebasestorage.app',
    iosBundleId: 'com.developeros.salasandbeats',
    iosClientId: '218086614765-dk3t4b8u29phfuhr0bq28nq3ojhe6is3.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlJjFhvaru7CHa5D4ivJYlVplwb8lbn10',
    appId: '1:787300819292:macos:3d184b81a2e636762ce199',
    messagingSenderId: '787300819292',
    projectId: 'salas-and-beats',
    storageBucket: 'salas-and-beats.firebasestorage.app',
    iosBundleId: 'com.developeros.salasandbeats',
  );
}